In [1]:
import pandas as pd
import json
from tqdm.notebook import tqdm

In [2]:
temp = []
file = open("yelp_academic_dataset_review.json", "r")
for line in tqdm(file.readlines()):
    temp.append(json.loads(line))
review_df = pd.DataFrame(temp)
review_df

  0%|          | 0/6990280 [00:00<?, ?it/s]

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5.0,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3.0,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4.0,1,0,1,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15
...,...,...,...,...,...,...,...,...,...
6990275,H0RIamZu0B0Ei0P4aeh3sQ,qskILQ3k0I_qcCMI-k6_QQ,jals67o91gcrD4DC81Vk6w,5.0,1,2,1,Latest addition to services from ICCU is Apple...,2014-12-17 21:45:20
6990276,shTPgbgdwTHSuU67mGCmZQ,Zo0th2m8Ez4gLSbHftiQvg,2vLksaMmSEcGbjI5gywpZA,5.0,2,1,2,"This spot offers a great, affordable east week...",2021-03-31 16:55:10
6990277,YNfNhgZlaaCO5Q_YJR4rEw,mm6E4FbCMwJmb7kPDZ5v2Q,R1khUUxidqfaJmcpmGd4aw,4.0,1,0,0,This Home Depot won me over when I needed to g...,2019-12-30 03:56:30
6990278,i-I4ZOhoX70Nw5H0FwrQUA,YwAMC-jvZ1fvEUum6QkEkw,Rr9kKArrMhSLVE9a53q-aA,5.0,1,0,0,For when I'm feeling like ignoring my calorie-...,2022-01-19 18:59:27
6990279,RwcKOdEuLRHNJe4M9-qpqg,6JehEvdoCvZPJ_XIxnzIIw,VAeEXLbEcI9Emt9KGYq9aA,3.0,10,3,7,Located in the 'Walking District' in Nashville...,2018-01-02 22:50:47

In [3]:
review_df.to_csv("reviews.csv")

In [4]:
temp = []
file = open("yelp_academic_dataset_business.json", "r")
for line in tqdm(file.readlines()):
    temp.append(json.loads(line))
business_df = pd.DataFrame(temp)
business_df

  0%|          | 0/150346 [00:00<?, ?it/s]

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",None
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,1,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150341,IUQopTMmYQG-qRtBk-8QnA,Binh's Nails,3388 Gateway Blvd,Edmonton,AB,T6J 5H2,53.468419,-113.492054,3.0,13,1,"{'ByAppointmentOnly': 'False', 'RestaurantsPri...","Nail Salons, Beauty & Spas","{'Monday': '10:0-19:30', 'Tuesday': '10:0-19:3..."
150342,c8GjPIOTGVmIemT7j5_SyQ,Wild Birds Unlimited,2813 Bransford Ave,Nashville,TN,37204,36.115118,-86.766925,4.0,5,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Pets, Nurseries & Gardening, Pet Stores, Hobby...","{'Monday': '9:30-17:30', 'Tuesday': '9:30-17:3..."
150343,_QAMST-NrQobXduilWEqSw,Claire's Boutique,"6020 E 82nd St, Ste 46",Indianapolis,IN,46250,39.908707,-86.065088,3.5,8,1,"{'RestaurantsPriceRange2': '1', 'BusinessAccep...","Shopping, Jewelry, Piercing, Toy Stores, Beaut...",None
150344,mtGm22y5c2UHNXDFAjaPNw,Cyclery & Fitness Center,2472 Troy Rd,Edwardsville,IL,62025,38.782351,-89.950558,4.0,24,1,"{'BusinessParking': '{'garage': False, 'street...","Fitness/Exercise Equipment, Eyewear & Optician...","{'Monday': '9:0-20:0', 'Tuesday': '9:0-20:0', ..."
150345,jV_XOycEzSlTx-65W906pg,Sic Ink,238 Apollo Beach Blvd,Apollo beach,FL,33572,27.771002,-82.394910,4.5,9,1,"{'WheelchairAccessible': 'True', 'BusinessAcce...","Beauty & Spas, Permanent Makeup, Piercing, Tattoo","{'Tuesday': '12:0-19:0', 'Wednesday': '12:0-19..."

In [5]:
business_df.to_csv("business.csv")

In [6]:
phl_business = business_df[business_df["city"] == "Philadelphia"]
phl_business

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
15,MUTTqe8uqyMdBl186RmNeA,Tuna Bar,205 Race St,Philadelphia,PA,19106,39.953949,-75.143226,4.0,245,1,"{'RestaurantsReservations': 'True', 'Restauran...","Sushi Bars, Restaurants, Japanese","{'Tuesday': '13:30-22:0', 'Wednesday': '13:30-..."
19,ROeacJQwBeh05Rqg7F6TCg,BAP,1224 South St,Philadelphia,PA,19147,39.943223,-75.162568,4.5,205,1,"{'NoiseLevel': 'u'quiet'', 'GoodForMeal': '{'d...","Korean, Restaurants","{'Monday': '11:30-20:30', 'Tuesday': '11:30-20..."
28,QdN72BWoyFypdGJhhI5r7g,Bar One,767 S 9th St,Philadelphia,PA,19147,39.939825,-75.157447,4.0,65,0,"{'Smoking': 'u'no'', 'NoiseLevel': 'u'average'...","Cocktail Bars, Bars, Italian, Nightlife, Resta...","{'Monday': '16:0-0:0', 'Tuesday': '16:0-0:0', ..."
31,Mjboz24M9NlBeiOJKLEd_Q,DeSandro on Main,4105 Main St,Philadelphia,PA,19127,40.022466,-75.218314,3.0,41,0,"{'RestaurantsReservations': 'False', 'Caters':...","Pizza, Restaurants, Salad, Soup","{'Tuesday': '17:0-21:30', 'Wednesday': '17:0-1..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150320,wPAaAbFbq5wfLfW0gnYU7g,Intermix,1718 Walnut St,Philadelphia,PA,19103,39.950060,-75.170129,2.0,10,0,"{'BusinessParking': '{'garage': False, 'street...","Fashion, Shopping, Women's Clothing","{'Monday': '10:0-19:0', 'Tuesday': '10:0-19:0'..."
150326,JDM7kiCEmeBc_5W-z6eZZw,2601 Parkway Apartments,2601 Pennsylvania Ave,Philadelphia,PA,19130,39.968806,-75.180608,3.0,6,1,{'BusinessAcceptsCreditCards': 'True'},"Real Estate, Apartments, Home Services",None
150329,9U1Igcpe954LoWZRmNc-zg,Hand & Stone Massage And Facial Spa,"1100 S Columbus Blvd, Ste 24",Philadelphia,PA,19147,39.932756,-75.144504,3.0,32,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Day Spas, Beauty & Spas, Skin Care, Massage","{'Monday': '9:0-22:0', 'Tuesday': '9:0-22:0', ..."
150334,LJ4GjQ1HL6kqvIPpNUNNaQ,Shanti Yoga and Ayurveda,"1638 Pine St, Fl 1",Philadelphia,PA,19103,39.945966,-75.169666,4.5,39,1,"{'ByAppointmentOnly': 'True', 'GoodForKids': '...","Health & Medical, Yoga, Shopping, Naturopathic...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
150336,WnT9NIzQgLlILjPT0kEcsQ,Adelita Taqueria & Restaurant,1108 S 9th St,Philadelphia,PA,19147,39.935982,-75.158665,4.5,35,1,"{'WheelchairAccessible': 'False', 'Restaurants...","Restaurants, Mexican","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'..."

In [7]:
b_r_df = pd.merge(review_df, phl_business, on="business_id", suffixes=("_review", "_business"))
b_r_df

,review_id,user_id,business_id,stars_review,useful,funny,cool,text,date,name,...,state,postal_code,latitude,longitude,stars_business,review_count,is_open,attributes,categories,hours
0,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5.0,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18,Body Cycle Spinning Studio,...,PA,19119,39.952103,-75.172753,5.0,144,0,"{'BusinessAcceptsCreditCards': 'True', 'GoodFo...","Active Life, Cycling Classes, Trainers, Gyms, ...","{'Monday': '6:30-20:30', 'Tuesday': '6:30-20:3..."
1,XwPeFvdm0-Z1XKj1pMepfA,BwSiqaeusSkkLRefYFB-Vg,7ATYjTIgM3jUlt4UM3IypQ,5.0,0,0,0,I've been going to Body Cycle for about a year...,2012-08-16 12:49:05,Body Cycle Spinning Studio,...,PA,19119,39.952103,-75.172753,5.0,144,0,"{'BusinessAcceptsCreditCards': 'True', 'GoodFo...","Active Life, Cycling Classes, Trainers, Gyms, ...","{'Monday': '6:30-20:30', 'Tuesday': '6:30-20:3..."
2,Pr4O2rvMF1HlQmIO3JnJcQ,d6H0HhqyOLiihCG6gbV4cg,7ATYjTIgM3jUlt4UM3IypQ,5.0,2,0,0,I started going to BCS in May or June of 2014....,2014-10-11 16:24:34,Body Cycle Spinning Studio,...,PA,19119,39.952103,-75.172753,5.0,144,0,"{'BusinessAcceptsCreditCards': 'True', 'GoodFo...","Active Life, Cycling Classes, Trainers, Gyms, ...","{'Monday': '6:30-20:30', 'Tuesday': '6:30-20:3..."
3,1OQV7ircjz7ztxGJ5vSBrA,yHy4xIfrENhYptOScwqHUA,7ATYjTIgM3jUlt4UM3IypQ,5.0,0,0,0,Love this Place! The instructors actually care...,2016-08-13 19:58:32,Body Cycle Spinning Studio,...,PA,19119,39.952103,-75.172753,5.0,144,0,"{'BusinessAcceptsCreditCards': 'True', 'GoodFo...","Active Life, Cycling Classes, Trainers, Gyms, ...","{'Monday': '6:30-20:30', 'Tuesday': '6:30-20:3..."
4,SkScixBp1dSxd9TCPjk-zw,uPr3t2M-OykA8M_oro7j1A,7ATYjTIgM3jUlt4UM3IypQ,4.0,1,0,1,Wow what a workout. I had Maria but it was her...,2013-07-14 19:54:29,Body Cycle Spinning Studio,...,PA,19119,39.952103,-75.172753,5.0,144,0,"{'BusinessAcceptsCreditCards': 'True', 'GoodFo...","Active Life, Cycling Classes, Trainers, Gyms, ...","{'Monday': '6:30-20:30', 'Tuesday': '6:30-20:3..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
967547,kpSp8muXCuByn-XrlAorLA,Z8obP1wG1uF84Di6IVnysQ,RROICJV1SdNKeua8QOSfhA,1.0,0,0,0,Mr.Katona is currently in legal proceedings be...,2021-07-08 21:53:17,Katona James A Sr Roofing,...,PA,19128,40.029744,-75.219088,2.0,5,1,None,"Home Services, Roofing",None
967548,GqT_L0FY5x9fisXKYJwZ-w,Z1Mm01Fc30REVNkf8H5M0Q,RROICJV1SdNKeua8QOSfhA,1.0,0,0,0,These two guys showed up to look at the roof o...,2019-09-04 14:43:07,Katona James A Sr Roofing,...,PA,19128,40.029744,-75.219088,2.0,5,1,None,"Home Services, Roofing",None
967549,NAbRKgCK0dBa2WoNTuyo5Q,TQJFeOOUIzcCJ0JSCP0mcw,RROICJV1SdNKeua8QOSfhA,1.0,2,0,0,"Jim repaired our leaking roof, and guaranteed ...",2018-02-11 16:45:38,Katona James A Sr Roofing,...,PA,19128,40.029744,-75.219088,2.0,5,1,None,"Home Services, Roofing",None
967550,s-nSyFnmI9iOIXQXhOIIzA,tdNshnSDbsC-xznoWN37HA,RROICJV1SdNKeua8QOSfhA,1.0,3,0,0,Jim does not like to write anything down. He m...,2018-12-18 04:27:52,Katona James A Sr Roofing,...,PA,19128,40.029744,-75.219088,2.0,5,1,None,"Home Services, Roofing",None
967551,t7ZCrgw9g4Cq07WWPOe9Yg,kpeQ1vV0J8UfOcFgTgcnZA,RROICJV1SdNKeua8QOSfhA,5.0,1,1,0,Jim was able to stop by the day I called (on a...,2018-02-13 14:25:46,Katona James A Sr Roofing,...,PA,19128,40.029744,-75.219088,2.0,5,1,None,"Home Services, Roofing",None

In [8]:
temp = []
file = open("yelp_academic_dataset_user.json", "r")
for line in tqdm(file.readlines()):
    temp.append(json.loads(line))
user_df = pd.DataFrame(temp)
user_df

  0%|          | 0/1987897 [00:00<?, ?it/s]

,user_id,name,review_count,yelping_since,useful,funny,cool,elite,friends,fans,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,qVc8ODYU5SZjKXVBgXdI7w,Walker,585,2007-01-25 16:47:26,7217,1259,5994,2007,"NSCy54eWehBJyZdG2iE84w, pe42u7DcCH2QmI81NX-8qA...",267,...,65,55,56,18,232,844,467,467,239,180
1,j14WgRoU_-2ZE1aw1dXrJg,Daniel,4333,2009-01-25 04:35:42,43091,13066,27281,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2...","ueRPE0CX75ePGMqOFVj6IQ, 52oH4DrRvzzl8wh5UXyU0A...",3138,...,264,184,157,251,1847,7054,3131,3131,1521,1946
2,2WnXYQFK0hXEoTxPtV2zvg,Steph,665,2008-07-25 10:41:00,2086,1010,1003,"2009,2010,2011,2012,2013","LuO3Bn4f3rlhyHIaNfTlnA, j9B4XdHUhDfTKVecyWQgyA...",52,...,13,10,17,3,66,96,119,119,35,18
3,SZDeASXq7o05mMNLshsdIA,Gwen,224,2005-11-29 04:38:33,512,330,299,"2009,2010,2011","enx1vVPnfdNUdPho6PH_wg, 4wOcvMLtU6a9Lslggq74Vg...",28,...,4,1,6,2,12,16,26,26,10,9
4,hA5lMy-EnncsH4JoR-hFGQ,Karen,79,2007-01-05 19:40:59,29,15,7,,"PBK4q9KEEBHhFvSXCUirIw, 3FWPpM7KU1gXeOM_ZbYMbA...",1,...,1,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1987892,fB3jbHi3m0L2KgGOxBv6uw,Jerrold,23,2015-01-06 00:31:31,7,0,0,,None,0,...,0,0,0,0,0,0,0,0,0,0
1987893,68czcr4BxJyMQ9cJBm6C7Q,Jane,1,2016-06-14 07:20:52,0,0,0,,None,0,...,0,0,0,0,0,0,0,0,0,0
1987894,1x3KMskYxOuJCjRz70xOqQ,Shomari,4,2017-02-04 15:31:58,1,1,0,,None,0,...,0,0,0,0,0,0,0,0,0,0
1987895,ulfGl4tdbrH05xKzh5lnog,Susanne,2,2011-01-14 00:29:08,0,0,0,,None,0,...,0,0,0,0,0,0,0,0,0,0
1987896,wL5jPrLRVCK_Pmo4lM1zpA,Isa,2,2020-12-19 02:32:39,0,0,0,,None,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
user_df.to_csv("users.csv")

In [10]:
b_r_u_df = pd.merge(b_r_df, user_df, on="user_id", suffixes=("", "_user"))
b_r_u_df

,review_id,user_id,business_id,stars_review,useful,funny,cool,text,date,name,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5.0,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18,Body Cycle Spinning Studio,...,0,0,0,0,0,0,0,0,0,0
1,sk6u1nDJVafRvfID_b8BKQ,OyoGAe7OKpv6SyGZT5g77Q,qjGS_7iaQDpbVhS6W8qkHQ,5.0,0,0,0,"Welcome to the neighborhood, Sweet Life Bakesh...",2015-04-16 16:34:29,The Sweet Life Bakeshop,...,0,0,0,0,0,0,0,0,0,0
2,5UuzfztGwOp8PqlShQMqcg,OyoGAe7OKpv6SyGZT5g77Q,cwn_MBPFUJtme68WURSgKA,1.0,3,1,0,We decided to give the Barrel House another sh...,2016-04-11 12:37:22,Bainbridge Street Barrel House,...,0,0,0,0,0,0,0,0,0,0
3,ZDnR9j9AAORY01AH_Z6CgQ,OyoGAe7OKpv6SyGZT5g77Q,Q93hDbLqgCHx9l1zmP5Gcg,5.0,0,0,0,These guys were fantastic! They moved my grand...,2018-11-07 15:17:25,Ivy Student Movers,...,0,0,0,0,0,0,0,0,0,0
4,XwPeFvdm0-Z1XKj1pMepfA,BwSiqaeusSkkLRefYFB-Vg,7ATYjTIgM3jUlt4UM3IypQ,5.0,0,0,0,I've been going to Body Cycle for about a year...,2012-08-16 12:49:05,Body Cycle Spinning Studio,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
967545,ByTnVhdF62jdHDm893Im5g,wpqQbJ-67hinmbjFATJKUw,0ikOz5a37dSa4dBGmEmdrg,5.0,2,0,0,Amazing customer experience. Locksmith was the...,2017-04-12 00:31:36,AMPM Locksmith - Philadelphia,...,0,0,0,0,0,0,0,0,0,0
967546,YX4NugGofam98n2bTAXX_g,K2rprvb3gasaQGxXY_mS0A,0ikOz5a37dSa4dBGmEmdrg,5.0,2,0,0,My tenant was locked out and I called Shay for...,2018-06-26 13:20:26,AMPM Locksmith - Philadelphia,...,0,0,0,0,0,0,0,0,0,0
967547,GqT_L0FY5x9fisXKYJwZ-w,Z1Mm01Fc30REVNkf8H5M0Q,RROICJV1SdNKeua8QOSfhA,1.0,0,0,0,These two guys showed up to look at the roof o...,2019-09-04 14:43:07,Katona James A Sr Roofing,...,0,0,0,0,0,0,0,0,0,0
967548,NAbRKgCK0dBa2WoNTuyo5Q,TQJFeOOUIzcCJ0JSCP0mcw,RROICJV1SdNKeua8QOSfhA,1.0,2,0,0,"Jim repaired our leaking roof, and guaranteed ...",2018-02-11 16:45:38,Katona James A Sr Roofing,...,0,0,0,0,0,0,0,0,0,0
967549,s-nSyFnmI9iOIXQXhOIIzA,tdNshnSDbsC-xznoWN37HA,RROICJV1SdNKeua8QOSfhA,1.0,3,0,0,Jim does not like to write anything down. He m...,2018-12-18 04:27:52,Katona James A Sr Roofing,...,0,0,0,0,0,1,0,0,0,0

In [11]:
final_cleaned = b_r_u_df.drop(["business_id", "user_id", "review_id"], axis=1)
final_cleaned

,stars_review,useful,funny,cool,text,date,name,address,city,state,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,5.0,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18,Body Cycle Spinning Studio,"1923 Chestnut St, 2nd Fl",Philadelphia,PA,...,0,0,0,0,0,0,0,0,0,0
1,5.0,0,0,0,"Welcome to the neighborhood, Sweet Life Bakesh...",2015-04-16 16:34:29,The Sweet Life Bakeshop,740 South St,Philadelphia,PA,...,0,0,0,0,0,0,0,0,0,0
2,1.0,3,1,0,We decided to give the Barrel House another sh...,2016-04-11 12:37:22,Bainbridge Street Barrel House,625-27 S 6th St,Philadelphia,PA,...,0,0,0,0,0,0,0,0,0,0
3,5.0,0,0,0,These guys were fantastic! They moved my grand...,2018-11-07 15:17:25,Ivy Student Movers,,Philadelphia,PA,...,0,0,0,0,0,0,0,0,0,0
4,5.0,0,0,0,I've been going to Body Cycle for about a year...,2012-08-16 12:49:05,Body Cycle Spinning Studio,"1923 Chestnut St, 2nd Fl",Philadelphia,PA,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
967545,5.0,2,0,0,Amazing customer experience. Locksmith was the...,2017-04-12 00:31:36,AMPM Locksmith - Philadelphia,621 N 2nd St,Philadelphia,PA,...,0,0,0,0,0,0,0,0,0,0
967546,5.0,2,0,0,My tenant was locked out and I called Shay for...,2018-06-26 13:20:26,AMPM Locksmith - Philadelphia,621 N 2nd St,Philadelphia,PA,...,0,0,0,0,0,0,0,0,0,0
967547,1.0,0,0,0,These two guys showed up to look at the roof o...,2019-09-04 14:43:07,Katona James A Sr Roofing,4384 Manayunk Ave,Philadelphia,PA,...,0,0,0,0,0,0,0,0,0,0
967548,1.0,2,0,0,"Jim repaired our leaking roof, and guaranteed ...",2018-02-11 16:45:38,Katona James A Sr Roofing,4384 Manayunk Ave,Philadelphia,PA,...,0,0,0,0,0,0,0,0,0,0
967549,1.0,3,0,0,Jim does not like to write anything down. He m...,2018-12-18 04:27:52,Katona James A Sr Roofing,4384 Manayunk Ave,Philadelphia,PA,...,0,0,0,0,0,1,0,0,0,0

In [12]:
final_cleaned.to_csv("data.csv")

In [13]:
sample = final_cleaned.sample(1500)
sample

,stars_review,useful,funny,cool,text,date,name,address,city,state,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
706076,5.0,0,0,0,"Incredible Food, staff, and atmosphere. I woul...",2020-07-24 04:07:52,Cafe La Maude,816 N 4th St,Philadelphia,PA,...,0,0,0,0,0,0,0,0,0,0
137254,4.0,0,0,0,Low key but best of what Old City had to offer...,2016-02-11 01:08:17,Marmont Steakhouse & Bar,222 Market St,Philadelphia,PA,...,0,0,0,0,0,0,0,0,0,0
475538,5.0,0,0,0,You can tell when you walk in by the attention...,2017-01-29 00:33:18,La Mula Terca,2053 S Beechwood St,Philadelphia,PA,...,0,0,0,0,0,0,0,0,0,0
101162,3.0,2,1,2,Big fat chicken wings with a crunch with a mea...,2010-01-03 07:49:43,CafÃ© Soho,468 W Cheltenham Ave,Philadelphia,PA,...,3,0,0,0,9,9,6,6,2,3
54689,3.0,2,0,2,I came here for dinner for the seasonally rota...,2014-12-29 17:19:13,Russet,1521 Spruce St,Philadelphia,PA,...,3,3,0,5,31,53,53,53,25,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6663,3.0,1,0,0,If you looking for an above average dive bar t...,2018-02-07 20:26:33,The Bayou Bar & Grill,4245 Main St,Philadelphia,PA,...,1,1,0,0,27,57,32,32,12,6
898470,4.0,1,0,0,OMG all I can say is they have the beat hoagie...,2014-05-01 20:52:36,The Fresh Grocer of Walnut,4001 Walnut St,Philadelphia,PA,...,0,0,0,0,0,0,0,0,0,0
682240,1.0,0,3,1,Did not even have a chance to eat brunch here....,2019-10-20 16:11:00,Valanni,1229 Spruce St,Philadelphia,PA,...,0,0,1,0,0,0,0,0,0,0
305983,5.0,4,1,2,Whipped Bakeshop is a friendly neighborhood co...,2021-03-08 12:03:19,Whipped Bakeshop,636 Belgrade St,Philadelphia,PA,...,2,1,0,0,63,46,60,60,16,32
766450,4.0,0,0,0,Definitely a pretty high end Italian restauran...,2011-02-16 04:57:40,Fork,306 Market St,Philadelphia,PA,...,5,1,0,0,2,0,5,5,2,0

In [14]:
sample.to_csv("sample.csv")